### ISSUE TITLE
examples wont work with elfldr

### ISSUE THREAD

**Issue by segobi** [CTurt/PS4-SDK#12] opened 2016-01-13 09:24 UTC
getting "not enough memory available" error when using ps4-sdk examples with elfldr - while elfldr libps4 examples seem to work fine.

**Comment by hitodama** [comment] 2016-01-13 10:36
That's a generic error message :) It means the process has crashed with sigsegv for some reason. To fix this, please try the following:
- Copy a libps4 example to a new location (say posix/pthread)
- Remove the old source file (main.c)
- Copy the ps4sdk example source files to source/
- Remove all init...() at the beginning of main
- Fix the include headers (remove non present ps.h, and module.h and include kernel.h, alter some header names as needed)

I will at some point recreate the examples. I can't directly include them for license reasons. If you need further help, feel free to open an issue under libps4-examples. Please note that this is not a bug in PS4SDK which is (or was?) primarily set up for CTurts needs and I am therefore closing it here.

**Closed as completed** 2016-01-13 10:43 UTC
